# config/local.yaml

app:
  env: dev
  port: "8080"
  url_length: 6
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "1483"
  dbname: "url_shortender"
  tablename: "short_urls"
  sslmode: "disable"